// Generated by scaffold.py. Progressive: the page is complete without this file.
(function () {
  var toggle = document.querySelector('.nav-toggle');
  var nav = document.getElementById('site-nav');
  if (toggle && nav) {
    var setOpen = function (open) {
      nav.setAttribute('data-open', open ? 'true' : 'false');
      toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
      toggle.querySelector('.icon--menu').hidden = open;
      toggle.querySelector('.icon--close').hidden = !open;
    };
    toggle.addEventListener('click', function () {
      setOpen(nav.getAttribute('data-open') !== 'true');
    });
    nav.addEventListener('click', function (event) {
      if (event.target.closest('a')) { setOpen(false); }
    });
    document.addEventListener('keydown', function (event) {
      if (event.key === 'Escape') { setOpen(false); }
    });
  }

  var form = document.querySelector('form[data-static-form]');
  if (form) {
    var status = form.querySelector('.form-status');
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      var invalid = form.querySelector(':invalid');
      if (invalid) {
        if (status) { status.textContent = 'Campo obrigatório'; }
        invalid.focus();
        return;
      }
      if (status) { status.textContent = 'Mensagem enviada. Retornamos em breve.'; }
      form.reset();
    });
  }

  var year = document.querySelector('[data-year]');
  if (year) { year.textContent = String(new Date().getFullYear()); }
})();
